### ISSUE TITLE
Set multiple breadcrumbs regardless of route

### ISSUE THREAD

**Issue by AndriesN** [udayvunnam/xng-breadcrumb#163]
## 🧩 Feature request
Set multiple breadcrumbs regardless of route
### Description
I would like to have the ability to add multiple breadcrumbs when I'm on a url.
Example:
route is `localhost:4200/path1`
then when I resolve data, I use that data to build my own breadcrumb path, I cannot do that as of right now. I can only set one breadcrumb using the `.set()` method.
### Describe the solution you'd like
I'd like a solution where I can inject the breadcrumbService and use an `.add()` function (maybe?) so I can add multiple breadcrumbs.

### Describe alternatives you've considered
I tried using multiple empty route paths with a breadcrumb, also tried ways to access the breadcrumb[] object but could not figure out how I can add multiple breadcrumbs to the array.

**Comment by gabrielbergoc** [comment]
I want this functionality too

**Comment by udayvunnam** [comment]
@AndriesN @gabrielbergoc Can you confirm the below understanding of the requirement

Instead of 

```
breadcrumbService.set('mentors', 'Mentor View');
breadcrumbService.set('mentor/:id', 'Uday Vunnam');
```

we want 
`breadcrumbService.add('mentors', 'Mentor View').add('mentor/:id', 'Uday Vunnam')`

to make it easy to define the dynamic breadcrumbs?

**Comment by gabrielbergoc** [comment]
That would work for me!
But maybe add the "add" method, not replace "set"? I don't know if it's possible...
Like, the current interface and behavior remain unchanged, but at page "x" I may want to add, besides "x", "y" and "z", so that they remain in the breadcrumbs if I navigate further, and when I navigate backwards, only "x > y > z" are removed.
And maybe another methods like "remove", "has", etc.

**Comment by AndriesN** [comment]
Yes, that would be great!

**Comment by udayvunnam** [comment]
not stale

**Comment by FedeTommi** [comment]
Any update on this?
