### ISSUE TITLE
Breadcrumb Links Not Working

### ISSUE THREAD

**Issue by thehaseebahmed** [udayvunnam/xng-breadcrumb#176]
### Description

Breadcrumbs are showing up but the URL is not clickable and in one of my local projects it is clickable but there is no href for the a tag. I tried looking at the code but couldn't find what could be the reason. Please take a look at the attached example and let me know if I'm doing something wrong in the setup.

#### 🔬 Minimal Reproduction

[StackBlitz code here](https://stackblitz.com/edit/xng-breadcrumbs-bug?file=src%2Fapp%2Fapp.component.ts).

**Comment by udayvunnam** [comment]
@thehaseebahmed 

The issue is in route definition where everything is defined flat

```
const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'home', component: HomeComponent },
  { path: 'contact', component: ContactComponent },
  { path: 'products', component: ProductsComponent },
  { path: 'product/:id', component: ProductComponent },
  { path: 'users', component: UsersComponent },
  { path: 'user/:id/:name', component: UserComponent },
];
```

Please try as shown in https://udayvunnam.github.io/xng-breadcrumb/#/where-to-define-breadcrumbs?id=with-component-and-its-children, **add children**. 

We could support multilevel path but that would need some enhancement
