### ISSUE TITLE
How to customize the breadcrumb

### ISSUE THREAD

**Issue by Hesesses** [udayvunnam/xng-breadcrumb#5]
Hello,

thank you very much for this plugin.

I was wondering how you can customize the look of the breadcrumb, css? separator?

**Comment by udayvunnam** [comment]
Hi @Hesesses, Thanks for opening this issue.

You can use custom separator as well as override styles.

**Custom separator:**
Breadcrumb by default uses '/' as the separator. To use custom separator pass it as input to the component like below.

```html
<xng-breadcrumb seperator=">"></xng-breadcrumb>
```

**Styling breadcrumbs:**
The library uses the least specific selectors possible in order to make it easy to override them.
you can override by changing the CSS for classes `.breadcrumb, .current-path, .separator etc` with ::ng-deep

```css
::ng-deep .breadcrumb {
  background-color: bisque;
  border: 1px solid;
}
```

please upgrade the library to latest release `npm i xng-breadcrumb@latest --save` to use these features

**Comment by Hesesses** [comment]
Thank you very much! 🙏

**Comment by udayvunnam** [comment]
Do let me know if you feel a feature is missing or not evident. Happy to help!

**Comment by Hesesses** [comment]
I will! I actually tried 3 or 4 different plugins and this seems to be absolutely the best one.
